### ISSUE TITLE
Type Error in creating Subpopulation

### ISSUE THREAD

**Issue by AishwaryaVerma** [robustness-gym/robustness-gym#25]
**Describe the bug**
I ran this code mentioned in the README.md

**To Reproduce**

1. Code snippet:
       
         from robustnessgym import Spacy, ScoreSubpopulation
        
        def length(batch, columns):
            """
            Length using cached Spacy tokenization.
            """
            column_name = columns[0]
            # Take advantage of previously cached Spacy informations
            tokens = Spacy.retrieve(batch, columns, proc_fns=Spacy.tokens)[column_name]
            return [len(tokens_) for tokens_ in tokens]
        
        # Create a subpopulation that buckets examples based on length
        length_subpopulation = ScoreSubpopulation(intervals=[(0, 10), (10, 20)],
                                                  score_fn=length)
        
        dataset, slices, membership = length_subpopulation(dataset, columns=['question'])
        # dataset is updated with slice information
        # slices is a list of 2 Slice objects
        # membership is a matrix of shape (n x 2)

3. Errors and traceback '....'
    
        ---------------------------------------------------------------------------
        TypeError                                 Traceback (most recent call last)
        <ipython-input-4-3a673fb6fabf> in <module>
             14                                           score_fn=length)
             15 
        ---> 16 dataset, slices, membership = length_subpopulation(dataset, columns=['question'])
             17 # dataset is updated with slice information
             18 # slices is a list of 2 Slice objects
        
        /opt/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/slicebuilders/slicebuilder.py in __call__(self, batch_or_dataset, columns, mask, store_compressed, store, num_proc, *args, **kwargs)
            132                 )
            133             # Slice a batch
        --> 134             return self.process_batch(
            135                 batch=batch_or_dataset,
            136                 columns=columns,
        
        /opt/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/slicebuilders/subpopulation.py in process_batch(self, batch, columns, mask, store_compressed, store, *args, **kwargs)
             52 
             53         # Apply the SliceMaker's core functionality
        ---> 54         slice_membership = self.apply(slice_membership, batch, columns, *args, **kwargs)
             55 
             56         # Store these slice labels
        
        /opt/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/slicebuilders/subpopulations/score.py in apply(self, slice_membership, batch, columns, *args, **kwargs)
            186         ), "Must have exactly one score per example."
            187 
        --> 188         return self.bin(scores=scores)
            189 
            190 
        
        /opt/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/slicebuilders/subpopulations/score.py in bin(self, scores)
             61         # Bin the scores
             62         return (
        ---> 63             (self.left_limits <= scores[:, np.newaxis])
             64             & (scores[:, np.newaxis] <= self.right_limits)
             65         ).astype(np.int32)
        
        TypeError: '>=' not supported between instances of 'int' and 'NoneType'

**System Information**
 - OS: Linux
 - Versions for RG and relevant dependencies :  `robustnessgym` (v0.0.2), `spacy` (v2.3.5)

**Comment by krandiash** [comment]
Hi, thanks for the bug report -- we've been addressing a bunch of issues behind the scenes, and should have good documentation and an updated README for RG in the next 7-10 days.

In the meantime, I recommend,
- upgrading to the latest RG version (0.0.3) which makes some changes to our API (`pip install --upgrade robustnessgym`)

Here's a code snippet that is tested with `v0.0.3`, let me know if you have trouble with this.

```python
from robustnessgym import Spacy, ScoreSubpopulation, Identifier, Dataset
from robustnessgym.core.decorators import prerequisites

dataset = Dataset.load_dataset('boolq', split='validation')
# `datasets` has made some updates, temporary workaround to set the dataset identifier that we'll fix in v0.0.4 
dataset._identifier = dataset.identifier.without('version')(version=dataset.info.version.version_str)

spacy = Spacy()
dataset = spacy(dataset, ['question'])

def length(batch, columns):
    """
    Length using cached Spacy tokenization.
    """
    column_name = columns[0]
    # Take advantage of previously cached Spacy informations
    tokens = Spacy.retrieve(batch, columns, proc_fns=Spacy.tokens)
    return [len(tokens_) for tokens_ in tokens]
 
# Create a subpopulation that buckets examples based on length
# `prerequisites` is a temporary workaround to specify that `length` requires Spacy to be cached
# this will not be required in v0.0.4 
length_subpopulation = prerequisites(Spacy)(ScoreSubpopulation)(
    identifiers=[Identifier('0-10'), Identifier('10-20')],
    intervals=[(0, 10), (10, 20)], 
    score_fn=length,
)

# v0.0.3 no longer modifies `dataset`
sls, mat = length_subpopulation(dataset, columns=['question'])
```

**Comment by AishwaryaVerma** [comment]
> 
> 
> Hi, thanks for the bug report -- we've been addressing a bunch of issues behind the scenes, and should have good documentation and an updated README for RG in the next 7-10 days.
> 
> In the meantime, I recommend,
> 
>     * upgrading to the latest RG version (0.0.3) which makes some changes to our API (`pip install --upgrade robustnessgym`)
> 
> 
> Here's a code snippet that is tested with `v0.0.3`, let me know if you have trouble with this.
> 
> ```python
> from robustnessgym import Spacy, ScoreSubpopulation, Identifier, Dataset
> from robustnessgym.core.decorators import prerequisites
> 
> dataset = Dataset.load_dataset('boolq', split='validation')
> # `datasets` has made some updates, temporary workaround to set the dataset identifier that we'll fix in v0.0.4 
> dataset._identifier = dataset.identifier.without('version')(version=dataset.info.version.version_str)
> 
> spacy = Spacy()
> dataset = spacy(dataset, ['question'])
> 
> def length(batch, columns):
>     """
>     Length using cached Spacy tokenization.
>     """
>     column_name = columns[0]
>     # Take advantage of previously cached Spacy informations
>     tokens = Spacy.retrieve(batch, columns, proc_fns=Spacy.tokens)
>     return [len(tokens_) for tokens_ in tokens]
>  
> # Create a subpopulation that buckets examples based on length
> # `prerequisites` is a temporary workaround to specify that `length` requires Spacy to be cached
> # this will not be required in v0.0.4 
> length_subpopulation = prerequisites(Spacy)(ScoreSubpopulation)(
>     identifiers=[Identifier('0-10'), Identifier('10-20')],
>     intervals=[(0, 10), (10, 20)], 
>     score_fn=length,
> )
> 
> # v0.0.3 no longer modifies `dataset`
> sls, mat = length_subpopulation(dataset, columns=['question'])
> ```

Thank you for replying. 

While running the code below with RG 0.0.3, I have met with this particular error.

**To Reproduce**

1. Code Snippet


          # Get a dataset
          from robustnessgym import Dataset
          dataset = Dataset.load_dataset('boolq')
          
          # Run the Spacy pipeline
          from robustnessgym import Spacy
          spacy = Spacy()
          # .. on the 'question' column of the dataset
          dataset = spacy(batch_or_dataset=dataset, 
                          columns=['question'])
          
          
          # Run the Stanza pipeline
          from robustnessgym import Stanza
          stanza = Stanza()
          # .. on both the question and passage columns of a batch
          dataset = stanza(batch_or_dataset=dataset[:32], 
                           columns=['question', 'passage'])
          
          # .. use any of the other built-in operations in Robustness Gym!
          
          
          # Or, create your own CachedOperation
          from robustnessgym import CachedOperation, Identifier
          from robustnessgym.core.decorators import singlecolumn
          
          # Write a silly function that operates on a single column of a batch
          @singlecolumn
          def silly_fn(batch, columns):
              """
              Capitalize text in the specified column of the batch.
              """
              column_name = columns[0]
              assert type(batch[column_name]) == str, "Must apply to text column."
              return [text.capitalize() for text in batch[column_name]] 
          
          # Wrap the silly function in a CachedOperation
          silly_op = CachedOperation(apply_fn=silly_fn,
                                     identifier=Identifier(_name='SillyOp'))
          
          # Apply it to a dataset
          dataset = silly_op(batch_or_dataset=dataset, 
                             columns=['question'])

2. Error and Traceback 



          ---------------------------------------------------------------------------
          TypeError                                 Traceback (most recent call last)
          <ipython-input-2-2a20b471f623> in <module>
                7 spacy = Spacy()
                8 # .. on the 'question' column of the dataset
          ----> 9 dataset = spacy(batch_or_dataset=dataset, 
               10                 columns=['question'])
               11 
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/cachedops/spacy.py in __call__(self, batch_or_dataset, columns, batch_size)
               98         batch_size: int = 8192,
               99     ) -> BatchOrDataset:
          --> 100         return super().__call__(batch_or_dataset, columns, batch_size)
              101 
              102     @property
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in __call__(self, batch_or_dataset, columns, batch_size)
              699         # Iterate over the columns and apply
              700         for column in columns:
          --> 701             batch_or_dataset = super(SingleColumnCachedOperation, self).__call__(
              702                 batch_or_dataset=batch_or_dataset,
              703                 columns=[column],
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in __call__(self, batch_or_dataset, columns, batch_size)
              660 
              661             # Apply the CachedOperation to the dataset
          --> 662             dataset = self.process_dataset(
              663                 dataset=batch_or_dataset,
              664                 columns=columns,
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in process_dataset(self, dataset, columns, batch_size)
              569         """Apply the cached operation to a dataset."""
              570 
          --> 571         return dataset.update(
              572             partial(self.process_batch, columns=columns),
              573             batched=True,
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/dataset.py in update(self, function, with_indices, batched, batch_size, drop_last_batch)
              496             dataset._dataset = output
              497         elif isinstance(output, InMemoryDataset):
          --> 498             dataset = copy(self)
              499             dataset._dataset = output
              500         elif output is None:
          
          /srv/conda/envs/robustnessgym/lib/python3.8/copy.py in copy(x)
               90         reductor = getattr(x, "__reduce_ex__", None)
               91         if reductor is not None:
          ---> 92             rv = reductor(4)
               93         else:
               94             reductor = getattr(x, "__reduce__", None)
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/dataset.py in __getstate__(self)
              716             "interactions": self.dumps_interactions(),
              717             # Identifier
          --> 718             "_identifier": self.identifier.dumps() if self.identifier else None,
              719             # Dataset
              720             "_dataset": self._dataset,
          
          /srv/conda/envs/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/identifier.py in dumps(self)
               77     def dumps(self):
               78         """Dump the identifier to JSON."""
          ---> 79         return json.dumps(self.__dict__)
               80 
               81     @staticmethod
          
          /srv/conda/envs/robustnessgym/lib/python3.8/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
              229         cls is None and indent is None and separators is None and
              230         default is None and not sort_keys and not kw):
          --> 231         return _default_encoder.encode(obj)
              232     if cls is None:
              233         cls = JSONEncoder
          
          /srv/conda/envs/robustnessgym/lib/python3.8/json/encoder.py in encode(self, o)
              197         # exceptions aren't as detailed.  The list call should be roughly
              198         # equivalent to the PySequence_Fast that ''.join() would do.
          --> 199         chunks = self.iterencode(o, _one_shot=True)
              200         if not isinstance(chunks, (list, tuple)):
              201             chunks = list(chunks)
          
          /srv/conda/envs/robustnessgym/lib/python3.8/json/encoder.py in iterencode(self, o, _one_shot)
              255                 self.key_separator, self.item_separator, self.sort_keys,
              256                 self.skipkeys, _one_shot)
          --> 257         return _iterencode(o, 0)
              258 
              259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
          
          /srv/conda/envs/robustnessgym/lib/python3.8/json/encoder.py in default(self, o)
              177 
              178         """
          --> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
              180                         f'is not JSON serializable')
              181 
          
          TypeError: Object of type Version is not JSON serializable

**Comment by krandiash** [comment]
Try using the code I provided in the previous comment, in particular the line 
```python
dataset._identifier = dataset.identifier.without('version')(version=dataset.info.version.version_str)
```
is necessary due to some upgrades on `datasets`, and will fix this error.

**Comment by AishwaryaVerma** [comment]
> dataset._identifier = dataset.identifier.without('version')(version=dataset.info.version.version_str)

Thank you!
It worked.
