### ISSUE TITLE
but do you know something  similar for tabular data - not specific for NLP?

### ISSUE THREAD

**Issue by Sandy4321** [robustness-gym/robustness-gym#30]
great code

but do you know something  similar for tabular data - not specific for NLP?

**Comment by krandiash** [comment]
Hi, thanks for your interest! 

You can actually load in tabular data into RG directly, and the end-to-end workflows should approximately work. I'm working on creating a very simple example for tabular data that should be up by next week. Do you have particular applications or datasets in mind that you would be interested in seeing supported?

**Comment by Sandy4321** [comment]
this data can be great to try 
https://www.kaggle.com/c/tabular-playground-series-feb-2021/data
Tabular Playground Series - Feb 2021

for example if you want only categorical data you can use these features:
cat0 - cat9 are categorical

**Comment by krandiash** [comment]
Thanks for the suggestion! I'll definitely try to put a simple example up with this or similar data. 

Out of curiosity, is this something that you'd be interested in seeing supported? Ideally we'd love to find use cases which folks in the community find very motivating.

**Comment by Sandy4321** [comment]
yes just add data with known patterns to test how different algorithms can find these patterns
for tabular data
I am very surprised why NOBODY doing this 

for example
for features A, B, C, D and binary target yes or no

A  B   C  D     target

a1 b3  c21     no
a2  b4  c2      no
a1  b1 c1       yes
a3  b4  c2      no
a1  b1  c1      yes
a1  b6  c5      yes
a6  b23 c8     no
a1 b23  c8     yes
a1 b23  c8     yes


there are 2 patterns for yes
a1  b1  c1
and
a1 b23  c8     yes

then by analogy you create 10 millions rows and 250 features and 578 categorical values for each feature
and you introduce lets say 
or 
30 patterns
or
200 patterns
or
1000 patterns

with pattern length from  5 to 20 features (random pattern length)

and ratio of number of no to number of yes = 1% -> unbalanced data 

this way we can test existing ML models for performance to find these patterns? 

I think they afraid from these data sets - since vast majority of ML packages are useless in this case 

lets do it?
Hinton: From a very young age I was convinced that many of the things that the teachers and other kids believed were just obvious nonsense. That’s great training for a scientist and it transferred very well to artificial intelligence

https://www.kdnuggets.com/2014/12/geoffrey-hinton-talks-deep-learning-google-everything.html

**Comment by Sandy4321** [comment]
adding word random :
then by analogy you create 10 million rows and 250 features and random 578 categorical values for

**Comment by Sandy4321** [comment]
by the way 
may I ask how your project is different from
https://github.com/Trusted-AI/adversarial-robustness-toolbox
