### ISSUE TITLE
[BUG] Cached operations not available in score_fn of ScoreSubpopulation

### ISSUE THREAD

**Issue by ajyeager** [robustness-gym/robustness-gym#33]
**Describe the bug**
Example in README using subpopulations uses a function which relies on cached spacy results, but these cached results are stripped from the dataset/batch before the length function is reached.

**To Reproduce**
Steps and code snippet that reproduce the behavior:

1. Code snippet (from the README)
```python
from robustnessgym import Dataset, Spacy, ScoreSubpopulation

dataset = Dataset.load_dataset('boolq', split='train')
spacy = Spacy()
# .. on the 'question' column of the dataset
dataset = spacy(batch_or_dataset=dataset, 
                columns=['question'])

def length(batch, columns):
    """
    Length using cached Spacy tokenization.
    """
    column_name = columns[0]
    # Take advantage of previously cached Spacy informations
    tokens = Spacy.retrieve(batch, columns, proc_fns=Spacy.tokens)[column_name]
    return [len(tokens_) for tokens_ in tokens]

# Create a subpopulation that buckets examples based on length
length_subpopulation = ScoreSubpopulation(intervals=[(0, 10), (10, 20)],
                                          score_fn=length)

dataset, slices, membership = length_subpopulation(dataset, columns=['question'])
```

2. Instructions: Run example above
3. Errors and traceback:

> ValueError: Retrieval failed: couldn't find a key called Spacy in cache.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-63-3a673fb6fabf> in <module>
>      14                                           score_fn=length)
>      15 
> ---> 16 dataset, slices, membership = length_subpopulation(dataset, columns=['question'])
>      17 # dataset is updated with slice information
>      18 # slices is a list of 2 Slice objects
> 
> /opt/notebooks/sandbox/Robustness/robustness-gym/robustnessgym/slicebuilders/slicebuilder.py in __call__(self, batch_or_dataset, columns, mask, num_proc, batch_size, *args, **kwargs)
>     116                 batch_size=batch_size,
>     117                 *args,
> --> 118                 **kwargs,
>     119             )
>     120 
> 
> /opt/notebooks/sandbox/Robustness/robustness-gym/robustnessgym/slicebuilders/subpopulations/score.py in prepare_dataset(self, dataset, columns, batch_size, *args, **kwargs)
>     128             batch_size=batch_size,
>     129             *args,
> --> 130             **kwargs,
>     131         )
>     132 
> 
> /opt/notebooks/sandbox/Robustness/robustness-gym/robustnessgym/slicebuilders/slicebuilder.py in prepare_dataset(self, dataset, columns, batch_size, *args, **kwargs)
>     263                         columns=columns,
>     264                         *args,
> --> 265                         **kwargs,
>     266                     )
>     267                 except NotImplementedError:
> 
> /opt/notebooks/sandbox/Robustness/robustness-gym/robustnessgym/slicebuilders/subpopulations/score.py in prepare_batch(self, batch, columns, *args, **kwargs)
>     140             self.scores.extend(self.score.retrieve(batch=batch, columns=columns))
>     141         elif isinstance(self.score, Callable):
> --> 142             self.scores.extend(self.score(batch=batch, columns=columns))
>     143         else:
>     144             raise RuntimeError("score function invalid.")
> 
> <ipython-input-63-3a673fb6fabf> in length(batch, columns)
>       7     column_name = columns[0]
>       8     # Take advantage of previously cached Spacy informations
> ----> 9     tokens = Spacy.retrieve(batch, columns, proc_fns=Spacy.tokens)[column_name]
>      10     return [len(tokens_) for tokens_ in tokens]
>      11 
> 
> /opt/notebooks/sandbox/Robustness/robustness-gym/robustnessgym/core/cachedops.py in retrieve(self_or_cls, batch, columns, proc_fns, identifier, reapply, **kwargs)
>     126                 if not identifier:
>     127                     raise ValueError(
> --> 128                         f"Retrieval failed: couldn't find a key called "
>     129                         f"{target_ident_key} in cache."
>     130                     )
> 
> ValueError: Retrieval failed: couldn't find a key called Spacy in cache.

Include any relevant screenshots.

**Expected behavior**
The `length` function would be able to use the Spacy results already computed on the 'question' column.

**System Information**
 - OS: Linux
 - Versions for RG and relevant dependencies [`robustnessgym` (v0.0.3), `spacy` (v2.3.5)]

**Additional context**
It appears a function called `_filter_prerequisite_columns` in slicebuilder is filtering out all columns except for 
"question" that was explicitly passed in.

**Comment by ajyeager** [comment]
Seeing now that the example code in a closed issue mentions the need for `prerequisites(Spacy)` until v0.0.4

**Comment by krandiash** [comment]
Yeah! Sorry about this issue, we should have a fix for this in the next release.
