### ISSUE TITLE
[BUG] pip install does not work on colab

### ISSUE THREAD

**Issue by demegire** [robustness-gym/robustness-gym#58]
**Describe the bug**
cant install using pip install robustnessgym in google colab

**To Reproduce**
!pip install robustnessgym returns the following error:

ERROR: Could not find a version that satisfies the requirement robustnessgym (from versions: none)
ERROR: No matching distribution found for robustnessgym

**System Information**
 - google colab

**Comment by krandiash** [comment]
Hi, `robustnessgym` is only pip installable with Python 3.8+ and unfortunately Colab doesn't support Python 3.8 natively yet. Workarounds to use Colab with Python 3.8 for this can be found online.
