### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WadoodAbdul** [robustness-gym/robustness-gym#6]
**Error while installing with pip on colab**

**To Reproduce**

`
!pip install robustnessgym
`

output:
`ERROR: Could not find a version that satisfies the requirement robustnessgym (from versions: none)
ERROR: No matching distribution found for robustnessgym`

**System Information**
 - OS:  Linux
           NAME="Ubuntu"
           VERSION="18.04.5 LTS (Bionic Beaver)"
 - Versions for RG and relevant dependencies  `robustnessgym` (v0.0.2),
 -  Python version: 3.6.9
 - pip verison: 19.3

**Comment by krandiash** [comment]
Thanks for reporting this -- we currently only support `python >= 3.8` and don't have plans to support 3.6/3.7 at the moment. 

I would recommend using a venv with python 3.8 (e.g. `conda create -n rgym-env python=3.8; conda activate rgym-env; pip install robustnessgym`).
