### ISSUE TITLE
[BUG] singlecolumn decorator 

### ISSUE THREAD

**Issue by malharjere** [robustness-gym/robustness-gym#9]
**Describe the bug**
I tried running the following code from the GitHub repo.

```
from robustnessgym import Dataset
from robustnessgym import Stanza
from robustnessgym import CachedOperation, Identifier
from robustnessgym.core.decorators import singlecolumn

dataset = Dataset.load_dataset('boolq')
dataset = Dataset.load_dataset('boolq', split='train[:10]')

stanza = Stanza()
dataset_stanza = stanza(batch_or_dataset=dataset[:32], columns=['question', 'passage'])

# Write a silly function that operates on a single column of a batch
@singlecolumn
def silly_fn(batch, columns):
    """
    Capitalize text in the specified column of the batch.
    """
    column_name = columns[0]
    assert type(batch[column_name]) == str, "Must apply to text column."
    return [text.capitalize() for text in batch[column_name]] 

silly_op = CachedOperation(apply_fn=silly_fn, identifier=Identifier(_name='SillyOp'))
dataset_silly = silly_op(batch_or_dataset=dataset_stanza, columns=['question'])
```

I get the following error for the very last line.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-77931878a4f6> in <module>
      1 # Apply it to a dataset
----> 2 dataset_silly = silly_op(batch_or_dataset=dataset_stanza, columns=['question'])

~/Desktop/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in __call__(self, batch_or_dataset, columns, batch_size)
    455 
    456             # Apply the CachedOperation
--> 457             return self.process_batch(batch=batch_or_dataset, columns=columns)
    458         else:
    459             raise NotImplementedError

~/Desktop/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in process_batch(self, batch, columns)
    325         encoded_outputs = [
    326             self.encode(example_output)
--> 327             for example_output in self.apply(batch=batch, columns=columns)
    328         ]
    329 

TypeError: _singlecolumn() missing 1 required positional argument: 'self'
```
**System Information**
 - OS: MacOS
 - `robustnessgym` (v0.0.2), `spacy` (v2.3.5)

**Comment by krandiash** [comment]
Thanks for reporting this: as a workaround, try removing the `@singlecolumn` decorator (currently, it acts as a way to assert that your function is being applied to only a single column). 

I'll push a fix for this in the next release.

**Comment by AishwaryaVerma** [comment]
> 
> 
> **Describe the bug**
> I tried running the following code from the GitHub repo.
> 
> ```
> from robustnessgym import Dataset
> from robustnessgym import Stanza
> from robustnessgym import CachedOperation, Identifier
> from robustnessgym.core.decorators import singlecolumn
> 
> dataset = Dataset.load_dataset('boolq')
> dataset = Dataset.load_dataset('boolq', split='train[:10]')
> 
> stanza = Stanza()
> dataset_stanza = stanza(batch_or_dataset=dataset[:32], columns=['question', 'passage'])
> 
> # Write a silly function that operates on a single column of a batch
> @singlecolumn
> def silly_fn(batch, columns):
>     """
>     Capitalize text in the specified column of the batch.
>     """
>     column_name = columns[0]
>     assert type(batch[column_name]) == str, "Must apply to text column."
>     return [text.capitalize() for text in batch[column_name]] 
> 
> silly_op = CachedOperation(apply_fn=silly_fn, identifier=Identifier(_name='SillyOp'))
> dataset_silly = silly_op(batch_or_dataset=dataset_stanza, columns=['question'])
> ```
> 
> I get the following error for the very last line.
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-44-77931878a4f6> in <module>
>       1 # Apply it to a dataset
> ----> 2 dataset_silly = silly_op(batch_or_dataset=dataset_stanza, columns=['question'])
> 
> ~/Desktop/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in __call__(self, batch_or_dataset, columns, batch_size)
>     455 
>     456             # Apply the CachedOperation
> --> 457             return self.process_batch(batch=batch_or_dataset, columns=columns)
>     458         else:
>     459             raise NotImplementedError
> 
> ~/Desktop/robustnessgym/lib/python3.8/site-packages/robustnessgym/core/cachedops.py in process_batch(self, batch, columns)
>     325         encoded_outputs = [
>     326             self.encode(example_output)
> --> 327             for example_output in self.apply(batch=batch, columns=columns)
>     328         ]
>     329 
> 
> TypeError: _singlecolumn() missing 1 required positional argument: 'self'
> ```
> 
> **System Information**
> 
>     * OS: MacOS
> 
>     * `robustnessgym` (v0.0.2), `spacy` (v2.3.5)

How did you solve this error then?
